name: 'Office 365 CLI'
description: 'Runs an Office 365 CLI script'
inputs:
  O365_CLI_SCRIPT_PATH:  
    description: 'Relative path of the script in your repo.'
  O365_CLI_SCRIPT:
    description: 'Office 365 CLI Script'
runs:
  using: 'docker'
  image: 'Dockerfile'
