name: Run Office 365 CLI script

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Run CLI Script
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Office 365 CLI Login
      uses: anoopt/test-login@v1
      env:
        ADMIN_USERNAME:  ${{ secrets.adminUsername }}
        ADMIN_PASSWORD:  ${{ secrets.adminPassword }}
    - name: Run Office 365 CLI script
      uses: ./
      env:
        # O365_CLI_SCRIPT: o365 spo mail send --webUrl https://anoopccdev1.sharepoint.com/sites/testgroup1 --to 'anoop@anoopccdev1.onmicrosoft.com' --subject 'Email sent via Office 365 CLI GitHub Action' --body '<h1>Office 365 CLI</h1>Email sent via <b>GitHub Action</b>.'
        O365_CLI_SCRIPT_PATH: /script/lists.sh
